/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    blog: Blog;
    bookings: Booking;
    features: Feature;
    testimonials: Testimonial;
    'legal-pages': LegalPage;
    promotions: Promotion;
    'time-slots': TimeSlot;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    features: FeaturesSelect<false> | FeaturesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'legal-pages': LegalPagesSelect<false> | LegalPagesSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'time-slots': TimeSlotsSelect<false> | TimeSlotsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'fr' | 'en';
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  /**
   * Ordre d'affichage (les nombres les plus petits apparaissent en premier)
   */
  order: number;
  /**
   * Nom du service
   */
  name: string;
  slug: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Image principale du service
   */
  image?: (string | null) | Media;
  /**
   * Vidéo du service (prioritaire sur les images si présente)
   */
  video?: (string | null) | Media;
  /**
   * Image "Avant" pour la comparaison
   */
  beforeImage?: (string | null) | Media;
  /**
   * Image "Après" pour la comparaison
   */
  afterImage?: (string | null) | Media;
  /**
   * Autoriser le choix de la quantité dans le formulaire de réservation
   */
  allowQuantity?: boolean | null;
  /**
   * Type de tarification pour ce service
   */
  pricingType: 'fixed' | 'per_m2' | 'min_price' | 'quote';
  /**
   * Prix fixe du service en euros
   */
  fixedPrice?: number | null;
  /**
   * Prix par m² en euros
   */
  pricePerM2?: number | null;
  /**
   * Commande minimum en m²
   */
  minimumOrder?: number | null;
  /**
   * Prix de départ en euros (affiché comme "À partir de X€")
   */
  startingPrice?: number | null;
  /**
   * Texte personnalisé pour le devis (ex: "Prix sur devis", "Nous contacter"...)
   */
  quoteInfo?: string | null;
  /**
   * (Déprécié) Informations de tarification - utiliser pricingType à la place
   */
  pricing?: string | null;
  /**
   * (Déprécié) Prix du service - utiliser fixedPrice/pricePerM2/startingPrice à la place
   */
  price?: number | null;
  /**
   * (Déprécié) Utiliser pricingType = "min_price" à la place
   */
  pricePrefix?: boolean | null;
  /**
   * Nombre de colonnes que prend ce service dans la grille (grille de 4 colonnes)
   */
  columnSpan?: ('1' | '2' | '3' | '4') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: string;
  title: string;
  /**
   * URL slug généré automatiquement
   */
  slug: string;
  /**
   * Résumé court de l'article
   */
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage: string | Media;
  author?: string | null;
  publishedAt: string;
  /**
   * Titre SEO
   */
  metaTitle?: string | null;
  /**
   * Description SEO
   */
  metaDescription?: string | null;
  /**
   * Mots-clés séparés par virgule
   */
  metaKeywords?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Liste des demandes de réservation reçues via le formulaire de contact
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: string;
  /**
   * Numéro de réservation auto-généré
   */
  bookingNumber?: number | null;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
  address: string;
  primaryService: {
    serviceId: string | Service;
    quantity: number;
    price?: number | null;
  };
  /**
   * Ancien format pour compatibilité - utiliser secondaryServices
   */
  secondaryService?: {
    hasSecondaryService?: boolean | null;
    serviceId?: (string | null) | Service;
    quantity?: number | null;
    price?: number | null;
    discountedPrice?: number | null;
  };
  /**
   * Services additionnels avec réduction appliquée
   */
  secondaryServices?:
    | {
        serviceId: string | Service;
        quantity: number;
        price: number;
        discountPercent?: number | null;
        discountedPrice?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Pourcentage de réduction appliqué aux services supplémentaires
   */
  discountPercent?: number | null;
  /**
   * Format texte pour compatibilité avec anciennes réservations
   */
  service?: string | null;
  /**
   * Créneaux horaires réservés
   */
  timeSlots?:
    | {
        date: string;
        startTime: string;
        endTime: string;
        id?: string | null;
      }[]
    | null;
  date: string;
  message?: string | null;
  /**
   * Photos du mobilier ou sol à nettoyer
   */
  photos?: (string | Media)[] | null;
  /**
   * Montant total calculé (hors frais supplémentaires)
   */
  totalAmount?: number | null;
  status?: ('pending' | 'contacted' | 'confirmed' | 'completed' | 'cancelled') | null;
  /**
   * Notes internes (non visibles par le client)
   */
  notes?: string | null;
  clientEmailSent?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Caractéristiques pour la section "Pourquoi nous choisir"
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features".
 */
export interface Feature {
  id: string;
  /**
   * Emoji ou caractère à afficher (ex: ✓, ⚡, 🌱, etc.)
   */
  icon: string;
  /**
   * Titre de la caractéristique
   */
  title: string;
  /**
   * Description de la caractéristique
   */
  description: string;
  /**
   * Ordre d'affichage (du plus petit au plus grand)
   */
  order?: number | null;
  /**
   * Afficher cette caractéristique
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Avis clients pour la section "Pourquoi nous choisir"
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  /**
   * Nom du client
   */
  customerName: string;
  /**
   * Titre/profession du client (optionnel)
   */
  customerTitle?: string | null;
  /**
   * URL de l'avatar ou emoji (ex: 👤, 🙍, etc.)
   */
  customerAvatar?: string | null;
  /**
   * Contenu de l'avis
   */
  content: string;
  /**
   * Note sur 5 étoiles
   */
  rating: number;
  /**
   * Date de l'avis (optionnel)
   */
  date?: string | null;
  /**
   * ✅ Avis modéré et validé
   */
  isApproved: boolean;
  /**
   * Afficher cet avis
   */
  isActive?: boolean | null;
  /**
   * Ordre d'affichage (du plus petit au plus grand)
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages".
 */
export interface LegalPage {
  id: string;
  /**
   * Titre de la page légale
   */
  title: string;
  /**
   * Sélectionner le type de page légale
   */
  slug: 'legal-notices' | 'general-terms';
  /**
   * Contenu de la page légale
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Titre SEO
   */
  metaTitle?: string | null;
  /**
   * Description SEO
   */
  metaDescription?: string | null;
  /**
   * Date de dernière mise à jour
   */
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: string;
  /**
   * Titre de l'offre promotionnelle (ex: "Offre de lancement")
   */
  title: string;
  /**
   * Description de l'offre (optionnel)
   */
  description?: string | null;
  /**
   * Pourcentage de réduction (0-100) - Optionnel, laisser vide pour afficher uniquement un message
   */
  discountPercentage?: number | null;
  /**
   * Activer/désactiver l'affichage de l'offre
   */
  isActive: boolean;
  /**
   * Date de début de l'offre (optionnel)
   */
  startDate?: string | null;
  /**
   * Date de fin de l'offre (optionnel)
   */
  endDate?: string | null;
  /**
   * Couleur de l'encart promotionnel
   */
  bannerColor?: ('primary' | 'red' | 'green' | 'orange') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Gérez les créneaux horaires disponibles pour les réservations
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-slots".
 */
export interface TimeSlot {
  id: string;
  displayTitle?: string | null;
  /**
   * Date du créneau
   */
  date: string;
  /**
   * Heure de début du créneau (durée: 2h)
   */
  startTime: '09:00' | '11:00' | '13:00' | '15:00' | '17:00';
  /**
   * Heure de fin du créneau
   */
  endTime: '11:00' | '13:00' | '15:00' | '17:00' | '19:00';
  /**
   * Statut actuel du créneau
   */
  status: 'available' | 'blocked' | 'pending' | 'confirmed';
  /**
   * Réservation liée à ce créneau (si applicable)
   */
  bookingId?: (string | null) | Booking;
  /**
   * Notes internes (raison du blocage, etc.)
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: string | Service;
      } | null)
    | ({
        relationTo: 'blog';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'bookings';
        value: string | Booking;
      } | null)
    | ({
        relationTo: 'features';
        value: string | Feature;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: string | Testimonial;
      } | null)
    | ({
        relationTo: 'legal-pages';
        value: string | LegalPage;
      } | null)
    | ({
        relationTo: 'promotions';
        value: string | Promotion;
      } | null)
    | ({
        relationTo: 'time-slots';
        value: string | TimeSlot;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  order?: T;
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  video?: T;
  beforeImage?: T;
  afterImage?: T;
  allowQuantity?: T;
  pricingType?: T;
  fixedPrice?: T;
  pricePerM2?: T;
  minimumOrder?: T;
  startingPrice?: T;
  quoteInfo?: T;
  pricing?: T;
  price?: T;
  pricePrefix?: T;
  columnSpan?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  publishedAt?: T;
  metaTitle?: T;
  metaDescription?: T;
  metaKeywords?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingNumber?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  address?: T;
  primaryService?:
    | T
    | {
        serviceId?: T;
        quantity?: T;
        price?: T;
      };
  secondaryService?:
    | T
    | {
        hasSecondaryService?: T;
        serviceId?: T;
        quantity?: T;
        price?: T;
        discountedPrice?: T;
      };
  secondaryServices?:
    | T
    | {
        serviceId?: T;
        quantity?: T;
        price?: T;
        discountPercent?: T;
        discountedPrice?: T;
        id?: T;
      };
  discountPercent?: T;
  service?: T;
  timeSlots?:
    | T
    | {
        date?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  date?: T;
  message?: T;
  photos?: T;
  totalAmount?: T;
  status?: T;
  notes?: T;
  clientEmailSent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "features_select".
 */
export interface FeaturesSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  description?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  customerName?: T;
  customerTitle?: T;
  customerAvatar?: T;
  content?: T;
  rating?: T;
  date?: T;
  isApproved?: T;
  isActive?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-pages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  metaTitle?: T;
  metaDescription?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  discountPercentage?: T;
  isActive?: T;
  startDate?: T;
  endDate?: T;
  bannerColor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "time-slots_select".
 */
export interface TimeSlotsSelect<T extends boolean = true> {
  displayTitle?: T;
  date?: T;
  startTime?: T;
  endTime?: T;
  status?: T;
  bookingId?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Logo affiché dans le header de toutes les pages
   */
  logo?: (string | null) | Media;
  /**
   * Image affichée en arrière-plan de la section hero de la page d'accueil
   */
  heroBackgroundImage?: (string | null) | Media;
  /**
   * Opacité du calque sombre sur l'image (0 = transparent, 1 = opaque)
   */
  heroOverlayOpacity?: number | null;
  /**
   * Titre qui apparaît dans les résultats de recherche
   */
  homeMetaTitle?: string | null;
  /**
   * Description qui apparaît dans les résultats de recherche
   */
  homeMetaDescription?: string | null;
  /**
   * Contenu affiché au-dessus de la section "Nos Services" sur la page d'accueil
   */
  servicesIntroText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Titre qui apparaît dans les résultats de recherche
   */
  blogMetaTitle?: string | null;
  /**
   * Description qui apparaît dans les résultats de recherche
   */
  blogMetaDescription?: string | null;
  /**
   * Image affichée en haut de la page à propos
   */
  aboutImage?: (string | null) | Media;
  /**
   * Titre principal de la page à propos
   */
  aboutTitle?: string | null;
  /**
   * Contenu descriptif affiché sur la page à propos
   */
  aboutText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Titre qui apparaît dans les résultats de recherche
   */
  aboutMetaTitle?: string | null;
  /**
   * Description qui apparaît dans les résultats de recherche
   */
  aboutMetaDescription?: string | null;
  /**
   * Numéro de téléphone affiché sur le site (format: +33XXXXXXXXX)
   */
  phoneNumber?: string | null;
  /**
   * Montant minimum requis pour pouvoir passer une réservation
   */
  minimumOrderAmount?: number | null;
  /**
   * Pourcentage de réduction appliqué aux services supplémentaires lors d'une réservation (ex: 20 = -20%)
   */
  additionalServiceDiscount?: number | null;
  /**
   * Texte affiché au-dessus du champ message dans le récapitulatif du formulaire de réservation
   */
  messageHint?: string | null;
  /**
   * Contenu affiché sous le titre de la page Tarifs/Pricing
   */
  pricingIntroText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Titre qui apparaît dans les résultats de recherche
   */
  pricingMetaTitle?: string | null;
  /**
   * Description qui apparaît dans les résultats de recherche
   */
  pricingMetaDescription?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  logo?: T;
  heroBackgroundImage?: T;
  heroOverlayOpacity?: T;
  homeMetaTitle?: T;
  homeMetaDescription?: T;
  servicesIntroText?: T;
  blogMetaTitle?: T;
  blogMetaDescription?: T;
  aboutImage?: T;
  aboutTitle?: T;
  aboutText?: T;
  aboutMetaTitle?: T;
  aboutMetaDescription?: T;
  phoneNumber?: T;
  minimumOrderAmount?: T;
  additionalServiceDiscount?: T;
  messageHint?: T;
  pricingIntroText?: T;
  pricingMetaTitle?: T;
  pricingMetaDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}